backend:
  name: git-gateway

site_url: https://affiliatenetwork.buzz
display_url: https://affiliatenetwork.buzz

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    slug: "{{slug}}"

    editor:
      preview: false

    fields:
      - label: Title
        name: title
        widget: string

      - label: Meta Description
        name: description
        widget: text

      - label: Featured Image URL
        name: image
        widget: string

      - label: Body
        name: body
        widget: markdown
